# Write your MySQL query statement below
SELECT P1.PRODUCT_ID, NEW_PRICE AS PRICE FROM PRODUCTS P1 WHERE (P1.CHANGE_DATE,P1.PRODUCT_ID) IN (SELECT MAX(P2.CHANGE_DATE), P2.PRODUCT_ID FROM PRODUCTS P2 WHERE P2.CHANGE_DATE <= '2019-08-16' GROUP BY P2.PRODUCT_ID)
UNION ALL
SELECT P1.PRODUCT_ID, 10 AS PRICE FROM PRODUCTS P1 GROUP BY P1.PRODUCT_ID HAVING MIN(P1.CHANGE_DATE) > '2019-08-16';